---
title: "XAMPP MySQL db"
---

1. Nainstalujeme XAMPP a spustíme a mrkneme do phpmyadmin

2. Vypneme jen MySQL server v XAMPP Control Panelu.

3. Stáhneme novou verzi. Složku `c:\xampp\mysql` přejmenujeme na `mysql_old` a rozbalíme novou verzi mariadb do složky `mysql`.

4. Nakopíruji 2 složky (backup, scripts) a 3 soubory (*.bat) z mysql_old do mysql a také my.ini z xampp/mysql_old/bin do xampp/mysql/bin.

5. V XAMPP Control Panelu klikneme na `Shell` a zadáme:

```cmd
mysql_install_db
```

6. Spustíme databázi v Xampp control panelu

7. V prohlížeči v phpMyAdmin jděte do záložky Import.
Najděte soubor v: `C:\xampp\phpMyAdmin\sql\create_tables.sql`.
Importujte tento soubor do phpMyAdmin, aby se vytvořily potřebné tabulky pro správu uživatelů a oprávnění.

8. Otevřete `C:\xampp\phpMyAdmin\config.inc.php`.

Najděte řádek:

```php
$cfg['Servers'][$i]['auth_type'] = 'config';
```

Zkuste ho změnit na:

```php
$cfg['Servers'][$i]['auth_type'] = 'cookie';
```
9. Ve stejném souboru zakomentujte 2 řádky (User for advanced features)

10. Přihlášení do phpmyadmin je root bez hesla. 

## Připojení djanga

Nainstalujeme klienta mysql pro Python:
```cmd
pip install mysqlclient 
```
V souboru `settings.py` upravíme nastavení pro připojení k databázi:
```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'blabla',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '', #Emptyforlocalhostthroughdomainsocketsor'127.0.0.1' for  through TCP.
        'PORT': '', # Set to empty string for default.
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}
```

Nyní můžeme spustit příkazy pro vytvoření databáze a migrace:

```cmd
python manage.py makemigrations
python manage.py migrate
python manage.py createsuperuser
```

Po úspěšném vytvoření superuživatele můžeme spustit vývojový server:

```cmd
python manage.py runserver
```

A přistoupit k administraci na adrese `http://localhost:8000/admin/` a přihlásit se pomocí vytvořeného superuživatele. Nyní můžete spravovat databázi přes admin rozhraní Django.


