project:
  type: website

website:
  title: "PVA"
  page-footer: 
    right: "This page is built with [Quarto](https://quarto.org/) ❤️"
  
  site-url: https://martinekpavel.github.io/vyuka/
  repo-url: https://github.com/martinekpavel/vyuka
  repo-actions: [edit, source, issue]  
  page-navigation: true
  
  navbar:
    left:
      #  - href: index.qmd
      #    text: Úvod
      - href: 202526-1d.qmd
        text: "1.D 2025/26"
      - href: 202526-3d.qmd
        text: "3.D 2025/26"
      - href: web_html/index.qmd
        text: "HTML"
      - text: "Algoritmy"
        href: web_algo/index.qmd
      - text: "Python"
        href: web_python/index.qmd
      - text: "Django"
        href: web_django/
      - text: "JavaScript"
        href: web_js/index.qmd
      - about.qmd

  sidebar:
    - title: "HTML"
      style: "docked"
      # background: light
      contents:
        - web_html/index.qmd
        - web_html/01uvod.qmd
        - web_html/02git.qmd
        - web_html/03html.qmd
        - web_html/04publish.qmd
        - web_html/05css.qmd
        - web_html/06menu.qmd
        - web_html/07mediaq.qmd
        - web_html/08portfolio.qmd
        - web_html/09search.qmd
        - web_html/10rekap.qmd
        - web_html/11projekt.qmd
        - web_html/12search.qmd
        - web_html/13webai.qmd    
    - title: "JavaScript"
      style: "docked"
      contents:
        - web_js/index.qmd
        - web_js/01lekcejs.qmd
        - web_js/02lekcejs.qmd
        - web_js/03lekcejs.qmd
        - web_js/04lekcejs.qmd
        - web_js/api.qmd
    - title: "Algoritmy"
      style: "docked"
      contents:
        - web_algo/index.qmd
        - web_algo/02diag.qmd
        - web_algo/03diag.qmd
    - title: "Python"
      style: "docked"
          # background: light
      contents:
        - web_python/index.qmd
        - web_python/01install.qmd
        - web_python/pl03.qmd
        - web_python/pl04.qmd
        - web_python/pl05.qmd
        - web_python/pl06.qmd
        - web_python/pl07.qmd
        - web_python/pl08.qmd
        - web_python/pl09.qmd
        - web_python/pl10.qmd
        - web_python/pl11.qmd
        - web_python/pl12.qmd

    - title: "Django"
      style: "docked"
          # background: light
      contents:
        - web_django/index.qmd
        - web_django/01hello.qmd
        - web_django/02apps.qmd
        - web_django/03template.qmd
        - web_django/04newyear.qmd
        - web_django/05tasks.qmd
        - web_django/06projekt1.qmd
        - web_django/07sql.qmd
        - web_django/08flights.qmd
        - web_django/09flights.qmd
        - web_django/10users.qmd

format:
  html:
    mermaid:
      theme: forest
    theme: 
      light: yeti
      dark: superhero
    # theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    # toc-title: Contents
    toc-location: right

lang: cs

# quarto publish gh-pages

