---
title: "Nezařazeno"
---

## Užitečné odkazy

- <https://quarto.org/docs/authoring/markdown-basics.html>
- <https://marvin-schmitt.com/blog/website-tutorial-quarto/>
- <https://quarto.org/docs/authoring/callouts.html>

### Proxmox
- [5 things I ALWAYS do after Proxmox installation](https://www.youtube.com/watch?v=pcnJdJVTzc8)

### Linuxové příkazy, co pořád zapomínám

- `lsb_release -a` - zjistí verzi Linuxu    
- `du -sh .*/` - zjistí velikost složek a souborů v aktuálním adresáři
- `df -h` - zjistí využití disků
- `free -h` - zjistí využití RAM
- `alias ll='ls -la --color=auto'` - vytvoří alias pro zobrazení detailního barevného seznamu


## Visual Studio Code

`Ctrl + ,` nastavení
`Alt + Shift + P` otevře příkazovou paletu
`Alt + Shift + F` naformátuje kód
`Alt + Z` zapíná a vypíná zalamování řádků
`Alt + šipka nahoru / dolů` přesune řádek nahoru / dolů
`Alt + Shift + šipka nahoru / dolů` zkopíruje blok kódu nahoru / dolů

Pokud máte kurzor v řádku, nemusíte ho označovat, operace kopírování, přesunu a mazání se provádí s celým řádkem.

`Alt + kliknutí myší` - umožní vložit více kurzorů a provést operaci na všech najednou

### Default cmd terminal 

```bash
"terminal.integrated.defaultProfile.windows": "Command Prompt",
```



